# Generated by Django 2.2.7 on 2019-11-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200)),
                ('post_time', models.DateTimeField(max_length=30)),
                ('text', models.TextField(blank=True, max_length=2000)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('dest_fb', models.BooleanField(default=False)),
                ('dest_insta', models.BooleanField(default=False)),
                ('dest_gm', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('f', 'facebook'), ('i', 'instagram'), ('g', 'groupme'), ('n', 'null')], default='n', max_length=30)),
                ('username', models.CharField(blank=True, max_length=40)),
                ('password', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
