# Generated by Django 2.2.6 on 2019-11-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200)),
                ('post_time', models.DateTimeField(max_length=30)),
                ('text', models.TextField(blank=True, max_length=2000)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
