# Generated by Django 2.2.7 on 2019-12-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='GroupMeGroups',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
