# Generated by Django 2.2.7 on 2019-11-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='account_type',
            field=models.CharField(choices=[('f', 'Facebook'), ('i', 'Instagram'), ('g', 'GroupMe'), ('n', 'Choose an Account type')], default='n', max_length=30),
        ),
    ]
