# Generated by Django 2.2.6 on 2019-12-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='title',
            field=models.TextField(blank=True, help_text='Not Required - Easier to look at a glance', max_length=200),
        ),
    ]
