# Generated by Django 2.2.7 on 2019-11-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='accounttype',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='credentials',
            name='account',
            field=models.CharField(choices=[('F', 'Facebook'), ('I', 'Instagram'), ('G', 'GroupMe')], default='Facebook', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
