# Generated by Django 2.2.6 on 2019-11-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Social',
        ),
    ]
