# Generated by Django 2.2.7 on 2019-12-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='GroupMeGroups',
        ),
    ]
