# Generated by Django 2.2.7 on 2019-12-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0002_auto_20191126_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
