# Generated by Django 2.2.7 on 2019-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0002_facebookposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='picture',
            field=models.ImageField(blank=True, help_text='Only pictures are supported through this tool', null=True, upload_to='H2O_Portal/static'),
        ),
    ]
