# Generated by Django 2.2.6 on 2019-12-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0002_auto_20191208_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
