# Generated by Django 2.2.6 on 2019-12-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0002_auto_20191207_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='picture',
            field=models.ImageField(null=True, upload_to='H2O_Portal/static'),
        ),
    ]
