# Generated by Django 2.2.7 on 2019-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0002_remove_socialpost_groupmegroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='GroupMeGroups',
            field=models.TextField(null=True),
        ),
    ]
