# Generated by Django 2.2.7 on 2019-12-11 14:48

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0002_auto_20191211_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='GroupMeGroups',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
