# Generated by Django 2.2.6 on 2019-12-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0002_auto_20191207_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='post_time',
            field=models.DateTimeField(help_text='(ex 1/31/2019 12:00 PM)', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='title',
            field=models.TextField(blank=True, help_text='(Used for the Scheduler)', max_length=200),
        ),
    ]
