# Generated by Django 2.2.6 on 2019-12-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0002_auto_20191206_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='title',
            field=models.TextField(blank=True, help_text='(Not Required, but is helpful for reviewing)', max_length=200),
        ),
    ]
