# Generated by Django 2.2.7 on 2019-12-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0003_auto_20191209_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookPosts',
        ),
    ]
