# Generated by Django 2.2.7 on 2019-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0003_auto_20191125_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='post_time',
            field=models.DateTimeField(help_text='day month year Hour (AM/PM) - (ex 1/31/2019 13:00)', max_length=30),
        ),
    ]
