# Generated by Django 2.2.7 on 2019-12-05 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('H2O_Portal', '0003_delete_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithSocials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebookaccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_account', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
