# Generated by Django 2.2.6 on 2019-12-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0003_auto_20191207_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='H2O_Portal/static'),
        ),
    ]
