# Generated by Django 3.0 on 2019-12-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0003_auto_20191211_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='picture',
            field=models.ImageField(blank=True, help_text='Only pictures are supported through this tool', null=True, upload_to=''),
        ),
    ]
