# Generated by Django 2.2.6 on 2019-12-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0004_auto_20191206_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
    ]
