# Generated by Django 2.2.7 on 2019-12-06 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0004_auto_20191206_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='H2O_Portal.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(related_name='_user_accounts_+', to='H2O_Portal.User'),
        ),
        migrations.CreateModel(
            name='FacebookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=255)),
                ('publish_timestamp', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='H2O_Portal.User')),
            ],
            options={
                'verbose_name_plural': 'Facebook Statuses',
                'ordering': ['publish_timestamp'],
            },
        ),
    ]
