# Generated by Django 2.2.7 on 2019-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0004_auto_20191126_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='post_time',
            field=models.DateTimeField(help_text='(ex 1/31/2019 12:00 PM)', max_length=30),
        ),
    ]
