# Generated by Django 3.0 on 2019-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0004_auto_20191212_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='picture',
            field=models.ImageField(blank=True, help_text='Only pictures are supported through this tool', null=True, upload_to='H2O_Portal/media'),
        ),
    ]
