# Generated by Django 2.2.7 on 2019-11-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0005_auto_20191126_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='post_time',
            field=models.DateTimeField(help_text='(ex 1/31/2019 13:00)', max_length=30),
        ),
    ]
