# Generated by Django 2.2.7 on 2019-12-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0005_socialpost_groupmegroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='GroupMeGroups',
        ),
    ]
