# Generated by Django 3.2.2 on 2021-05-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0006_auto_20191212_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='post_time',
            field=models.DateTimeField(help_text='Type date or click on the arrow for calendar to select a date:', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
