# Generated by Django 3.2.2 on 2021-05-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0012_alter_socialpost_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='socialpost',
            name='Instagram',
            field=models.BooleanField(default=False),
        ),
    ]
