# Generated by Django 3.2.2 on 2021-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H2O_Portal', '0013_auto_20210530_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_username',
            field=models.TextField(blank=True, help_text='Instagram Password', null=True),
        ),
    ]
