# Generated by Django 2.2.6 on 2019-11-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField()),
                ('text', models.CharField(max_length=2000)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
