# Generated by Django 2.2.6 on 2019-11-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2o_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='authtype',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='h2o_portal/h2oLogo.png', upload_to='h2o_portal/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
