# Generated by Django 2.2.6 on 2019-11-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h2o_portal', '0002_auto_20191107_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
